### PR TITLE
Support puppet v3 with future parser and puppet v4

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici Have you seen this recently? Failing with strict variables because of operatingsystemmajrelease. The version of Facter looks good.. problem with the travis container?

**Comment by Phil-Friderici** [comment]
The failing test [1] sets lsbmajdistrelease but needed [2] operatingsystemmajrelease is missing.

[1] https://github.com/ghoneycutt/puppet-module-timezone/blob/puppet3_future_and_puppet4/spec/classes/init_spec.rb#L90-L98
[2] https://github.com/ghoneycutt/puppet-module-timezone/blob/master/manifests/init.pp#L40-L43

Same is true for for the arc parameter tests.

Strict variables tests are not forgiving anymore like in the past. If a variable is used but not defined it fails since the introduction of Puppet 4.4. Before that, a variable called but not defined was handled like undef.

**Comment by ghoneycutt** [comment]
Thanks @Phil-Friderici !

**Comment by Phil-Friderici** [comment]
tests fails because of missmatching code vs specs

https://github.com/ghoneycutt/puppet-module-timezone/blob/master/manifests/init.pp#L43

Guess that you need to remove the colon from release variable here
https://github.com/ghoneycutt/puppet-module-timezone/blob/master/spec/classes/init_spec.rb#L21

never mind, now I see you did already :)

**Comment by Phil-Friderici** [comment]
well, you need to move these line into the if/else statement:

https://github.com/ghoneycutt/puppet-module-timezone/blob/puppet3_future_and_puppet4/spec/classes/init_spec.rb#L32-L35

**Comment by Phil-Friderici** [comment]
took over the work in https://github.com/ghoneycutt/puppet-module-timezone/pull/3

**Pull request merged**
